language: java

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./setup_openfire.sh

script: ./gradlew clean build endtoendTest --info

jdk:
  - oraclejdk8

env:
  - TERM=dumb

deploy:
  provider: heroku
  api_key:
    secure: "hbLWGR3B8OtbSBC9NMuMoXOLgEwmuefGD4i7s4gkF1L7K85fAyTnIfDfq1zBxRwslmifWLrGo4jSzJ07alGlXlkPljs5u6Pblo2dJCJXc7dVvwqnpm9S8RI8j1NFRFW9oceUlTa+X2S7zCTginCrIOFuZgfhr2ZrQASfWrFuXftIFTtxB8+Zvx/wI7V+xGcvL3n0jra6E++6lOBALkYEBDQGb91n6wIHiqvJbWGusO0oeZj+i8jeTXLukHUNowFAd7mKcm9R9XQB8yZKE9Qi6su9uZXqaPWEhLrwCkeUfgXL1j2w5ODPC2fwfWTNQBpLItO6zGck3nZkFpiMfeafXtcZzSHvJ8mIsbIBcH5x3AyubS0+qapHw9xnyDQ940deTtNnefkR/jq33qiO8jL0JWH/x76CBtHhjVLMjyOv/XtYVwBDBWCFt4IFMUlfxPLto6eBbZufGcViPpUrGC9Qjk3yUEH7qHoFBEkC/dYG/6/F5FELXIMUuTo8OfUJ14e991YRlqURQqezdlLcjuy/sQsd+Rhplctuvv7s9rtePaLUpt5SAhpgfCkDabjrC9ihGv2stOYsbjGs+IKSDckTJLJIW2uZXdkJwr80B/M/5YYlvPq+BJB15Wc9AWEov6ot3i65rYG+1TdgqmM76kCOrjzQBHSsu5nEyfZYYJ1wt2I="

after_success:
  - ./gradlew jacocoEndtoendTestReport coveralls --info

after_script:
  - kill $(cat server/openfire.pid)
